const items = [
    {
        id: '1',
        image: 'images/1.jpg',
        company: 'Sangria',
        item_name: 'Senquinned Embelished Saree',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '21 Sep 2024',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '2',
        image: 'images/2.jpg',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Saree',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '28 Sep 2024',
        rating: {
            stars: 4.3,
            count: 2400,
        },
    },
    {
        id: '3',
        image: 'images/3.jpg',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.1,
            count: 2249,
        },
    },
    {
        id: '4',
        image: 'images/4.jpg',
        company: 'RARE RABBIT',
        item_name: 'Men Zanza Plain Suit',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '15 Oct 2024',
        rating: {
            stars: 5.0,
            count: 1000,
        },
    },
    {
        id: '5',
        image: 'images/5.jpg',
        company: 'Raymond',
        item_name: 'Mens Quartz Suit',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '18 Sep 2024',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '6',
        image: 'images/6.jpg',
        company: 'Arrow',
        item_name: 'Men ReactX Suit',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '20 Sep 2024',
        rating: {
            stars: 1.5,
            count: 1600,
        },
    },
    {
        id: '7',
        image: 'images/7.jpg',
        company: 'Zara',
        item_name: 'Men Slim Fit Regular Suit',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        return_period: 14,
        delivery_date: '21 Sep 2024',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '8',
        image: 'images/8.jpg',
        company: 'Peterland',
        item_name: 'Men coartz Suit',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        return_period: 14,
        delivery_date: '27 Sep 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },

    {
        id: '9',
        image: 'images/9.jpg',
        company: 'Raymond',
        item_name: 'Jents Kurta',
        original_price: 885,
        current_price: 542,
        discount_percentage: 30,
        return_period: 14,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },

    {
        id: '10',
        image: 'images/10.jpg',
        company: 'Kalini',
        item_name: 'Embroidered straight Kurta set',
        original_price: 805,
        current_price: 642,
        discount_percentage: 20,
        return_period: 14,
        delivery_date: '15 set 2024',
        rating: {
            stars: 4.2,
            count: 6200,
        },
    },

    {
        id: '11',
        image: 'images/11.jpg',
        company: 'Sriram',
        item_name: 'Mens Kurta',
        original_price: 1500,
        current_price: 1001,
        discount_percentage: 40,
        return_period: 24,
        delivery_date: '10 Oct 2024',
        rating: {
            stars: 4.2,
            count: 7200,
        },
    },

    {
        id: '12',
        image: 'images/12.jpg',
        company: 'GoSriki',
        item_name: 'Printed Straight Kurta Set',
        original_price: 4345,
        current_price: 999,
        discount_percentage:77,
        return_period: 14,
        delivery_date: '20 set 2024',
        rating: {
            stars: 5.0,
            count: 4000,
        },
    },

    {
        id: '13',
        image: 'images/13.jpg',
        company: 'WoodenTant',
        item_name: 'Pure Cotton Tant Saree',
        original_price: 3000,
        current_price: 899,
        discount_percentage: 80,
        return_period: 14,
        delivery_date: '15 Sep 2024',
        rating: {
            stars: 4.5,
            count: 7200,
        },
    }
];